package com.sentinelmesh.realtime;

public enum DashboardEventType 
{
	DEVICE_REGISTERED,
	DEVICE_HEARTBEAT_RECEIVED,
	DEVICE_STATUS_CHANGED,
	SECURITY_EVENT_CREATED,
	ALERT_CREATED,
	ALERT_ACKNOWLEDGED,
	ALERT_RESOLVED,
	RULE_CREATED,
	RULE_UPDATED,
	RULE_DELETED
}
